"""What an error code means, and the exceptions raised for one."""

from __future__ import annotations

from pylabrobot.agilent.biotek.lhc.error_handling.errors import (
  NO_ERROR,
  NOT_ACKNOWLEDGED,
  PORT_WOULD_NOT_OPEN,
  REPLY_TIMED_OUT,
  UNKNOWN_CODE,
  WRITE_FAILED,
  AbortedError,
  BiotekError,
  ErrorInfo,
  ErrorKind,
  FirmwareError,
  FluidicsError,
  LinkError,
  MotorError,
  RejectedError,
  SensorError,
  ServiceTestError,
  StorageError,
  classify,
  describe,
  error_message,
  fail,
  for_info,
  info_for,
  normalize,
  raise_for_status,
)

__all__ = [
  "NO_ERROR",
  "NOT_ACKNOWLEDGED",
  "PORT_WOULD_NOT_OPEN",
  "REPLY_TIMED_OUT",
  "UNKNOWN_CODE",
  "WRITE_FAILED",
  "AbortedError",
  "BiotekError",
  "ErrorInfo",
  "ErrorKind",
  "FirmwareError",
  "FluidicsError",
  "LinkError",
  "MotorError",
  "RejectedError",
  "SensorError",
  "ServiceTestError",
  "StorageError",
  "classify",
  "describe",
  "error_message",
  "fail",
  "for_info",
  "info_for",
  "normalize",
  "raise_for_status",
]
